[2023-10-01T17:18:12.918+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2023-10-01T17:18:12.932+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2023-10-01T17:18:12.933+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 3
[2023-10-01T17:18:13.085+0000] {taskinstance.py:1327} INFO - Executing <Task(WebToGCSHKOperator): download_to_gcs> on 2019-07-02 06:00:00+00:00
[2023-10-01T17:18:13.093+0000] {standard_task_runner.py:57} INFO - Started process 2102 to run task
[2023-10-01T17:18:13.097+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-BQ', 'download_to_gcs', 'scheduled__2019-07-02T06:00:00+00:00', '--job-id', '597', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_bq.py', '--cfg-path', '/tmp/tmpaf_23jax']
[2023-10-01T17:18:13.100+0000] {standard_task_runner.py:85} INFO - Job 597: Subtask download_to_gcs
[2023-10-01T17:18:13.296+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-07-02T06:00:00+00:00 [running]> on host 772c7a5949f4
[2023-10-01T17:18:14.170+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-BQ' AIRFLOW_CTX_TASK_ID='download_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2019-07-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-07-02T06:00:00+00:00'
[2023-10-01T17:18:14.172+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-01T17:18:14.173+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-01T17:18:14.174+0000] {Web_To_GCS_Hook.py:67} INFO - Execute downloading of file from https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-07.csv.gz to gs://practice18//green_tripdata_2019-07.csv.gz
[2023-10-01T17:18:14.183+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 721, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fef855033d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-07.csv.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef855033d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/plugins/web/operators/Web_To_GCS_Hook.py", line 58, in execute
    self._copy_file_object(gcs_hook)
  File "/opt/airflow/plugins/web/operators/Web_To_GCS_Hook.py", line 75, in _copy_file_object
    r = requests.get(request_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-07.csv.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef855033d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2023-10-01T17:18:14.196+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-BQ, task_id=download_to_gcs, execution_date=20190702T060000, start_date=20231001T171812, end_date=20231001T171814
[2023-10-01T17:18:14.423+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 597 for task download_to_gcs (HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-07.csv.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef855033d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')); 2102)
[2023-10-01T17:18:14.472+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-01T17:18:14.512+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01T18:04:56.827+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2023-10-01T18:04:56.917+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2023-10-01T18:04:56.917+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 3
[2023-10-01T18:04:56.948+0000] {taskinstance.py:1327} INFO - Executing <Task(WebToGCSHKOperator): download_to_gcs> on 2019-07-02 06:00:00+00:00
[2023-10-01T18:04:56.958+0000] {standard_task_runner.py:57} INFO - Started process 2808 to run task
[2023-10-01T18:04:56.962+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-BQ', 'download_to_gcs', 'scheduled__2019-07-02T06:00:00+00:00', '--job-id', '612', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_bq.py', '--cfg-path', '/tmp/tmp_m3or4g1']
[2023-10-01T18:04:56.965+0000] {standard_task_runner.py:85} INFO - Job 612: Subtask download_to_gcs
[2023-10-01T18:04:57.029+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.download_to_gcs scheduled__2019-07-02T06:00:00+00:00 [running]> on host 772c7a5949f4
[2023-10-01T18:04:57.156+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-BQ' AIRFLOW_CTX_TASK_ID='download_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2019-07-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-07-02T06:00:00+00:00'
[2023-10-01T18:04:57.158+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-01T18:04:57.158+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-01T18:04:57.158+0000] {Web_To_GCS_Hook.py:67} INFO - Execute downloading of file from https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-07.csv.gz to gs://practice18//green_tripdata_2019-07.csv.gz
[2023-10-01T18:05:43.111+0000] {Web_To_GCS_Hook.py:79} INFO - File written to temporary directory: /tmp/tmpb4d_ktcg/green_tripdata_2019-07.csv.gz
[2023-10-01T18:05:44.734+0000] {warnings.py:110} WARNING - /opt/***/plugins/web/operators/Web_To_GCS_Hook.py:58: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  self._copy_file_object(gcs_hook)

[2023-10-01T18:05:44.980+0000] {logging_mixin.py:150} INFO -    VendorID lpep_pickup_datetime  ... trip_type congestion_surcharge
0       2.0  2019-07-01 00:00:48  ...       1.0                  0.0
1       2.0  2019-07-01 00:23:36  ...       1.0                  0.0
2       2.0  2019-07-01 00:09:48  ...       1.0                  0.0
3       2.0  2019-07-01 00:09:07  ...       1.0                  0.0
4       2.0  2019-07-01 00:50:45  ...       1.0                  0.0

[5 rows x 20 columns]
[2023-10-01T18:05:50.767+0000] {Web_To_GCS_Hook.py:90} INFO - Parquet: green_tripdata_2019-07.csv
[2023-10-01T18:06:31.672+0000] {gcs.py:538} INFO - File /tmp/tmpb4d_ktcg/green_tripdata_2019-07.csv uploaded to green/green_tripdata_2019-07.csv in practice18 bucket
[2023-10-01T18:06:31.672+0000] {Web_To_GCS_Hook.py:105} INFO - Loaded file from https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-07.csv.gz to gs://practice18//green/green_tripdata_2019-07.csv
[2023-10-01T18:06:31.716+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-BQ, task_id=download_to_gcs, execution_date=20190702T060000, start_date=20231001T180456, end_date=20231001T180631
[2023-10-01T18:06:31.802+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-10-01T18:06:31.835+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
