[2023-10-01T17:45:20.821+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2023-10-01T17:45:24.308+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2023-10-01T17:45:24.309+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-10-01T17:45:24.679+0000] {taskinstance.py:1327} INFO - Executing <Task(GCSToBigQueryOperator): load_gcs_to_bigquery> on 2019-04-02 06:00:00+00:00
[2023-10-01T17:45:24.731+0000] {standard_task_runner.py:57} INFO - Started process 2490 to run task
[2023-10-01T17:45:24.736+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-BQ', 'load_gcs_to_bigquery', 'scheduled__2019-04-02T06:00:00+00:00', '--job-id', '606', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_bq.py', '--cfg-path', '/tmp/tmpiocxiip6']
[2023-10-01T17:45:24.739+0000] {standard_task_runner.py:85} INFO - Job 606: Subtask load_gcs_to_bigquery
[2023-10-01T17:45:25.508+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-04-02T06:00:00+00:00 [running]> on host 772c7a5949f4
[2023-10-01T17:45:27.135+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-BQ' AIRFLOW_CTX_TASK_ID='load_gcs_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2019-04-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-04-02T06:00:00+00:00'
[2023-10-01T17:45:27.137+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-01T17:45:27.137+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-01T17:45:27.138+0000] {gcs_to_bigquery.py:373} INFO - Using existing BigQuery table for storing data...
[2023-10-01T17:45:28.986+0000] {bigquery.py:2326} INFO - Project is not included in destination_project_dataset_table: alt_data.green_alt_data_table; using project "nature-26092023"
[2023-10-01T17:45:28.987+0000] {gcs_to_bigquery.py:377} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'nature-26092023', 'datasetId': 'alt_data', 'tableId': 'green_alt_data_table'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://practice18/green/green_tripdata_2019-04.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2023-10-01T17:45:28.987+0000] {bigquery.py:1592} INFO - Inserting job ***_Load_Green_Taxi_Data_Web_To_GCS_To_BQ_load_gcs_to_bigquery_2019_04_02T06_00_00_00_00_f5ab3b65adc7306a82270fd653d91d31
[2023-10-01T17:45:32.871+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef8553bd90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:45:32.872+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854e9150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:45:32.874+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854e9510>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:45:33.380+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854f1090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:45:33.382+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854f1450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:45:33.383+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854f1810>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:45:34.638+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854e9910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:45:34.639+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854e9450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:45:34.640+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef8553b690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:45:38.019+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854fc410>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:45:38.021+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854fc7d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:45:38.022+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854fcb90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:45:38.182+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef85484790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:45:38.183+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef85484b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:45:38.184+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef85484f10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:45:53.188+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854fce50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:45:53.189+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854fc710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:45:53.191+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854fc290>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:46:08.519+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef8553b450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:46:08.520+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854e96d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:46:08.521+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854e90d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:46:36.730+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef85490b90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:46:36.731+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef85490f90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:46:36.733+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854973d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:47:49.506+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-BQ, task_id=load_gcs_to_bigquery, execution_date=20190402T060000, start_date=20231001T174524, end_date=20231001T174749
[2023-10-01T17:47:51.963+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-10-01T17:47:52.029+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01T20:01:31.315+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2023-10-01T20:01:31.337+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-04-02T06:00:00+00:00 [queued]>
[2023-10-01T20:01:31.337+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-10-01T20:01:31.371+0000] {taskinstance.py:1327} INFO - Executing <Task(GCSToBigQueryOperator): load_gcs_to_bigquery> on 2019-04-02 06:00:00+00:00
[2023-10-01T20:01:31.380+0000] {standard_task_runner.py:57} INFO - Started process 4786 to run task
[2023-10-01T20:01:31.383+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-BQ', 'load_gcs_to_bigquery', 'scheduled__2019-04-02T06:00:00+00:00', '--job-id', '636', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_bq.py', '--cfg-path', '/tmp/tmprh6_vrcp']
[2023-10-01T20:01:31.388+0000] {standard_task_runner.py:85} INFO - Job 636: Subtask load_gcs_to_bigquery
[2023-10-01T20:01:31.443+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-04-02T06:00:00+00:00 [running]> on host 772c7a5949f4
[2023-10-01T20:01:31.594+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-BQ' AIRFLOW_CTX_TASK_ID='load_gcs_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2019-04-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-04-02T06:00:00+00:00'
[2023-10-01T20:01:31.596+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-01T20:01:31.596+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-01T20:01:31.597+0000] {gcs_to_bigquery.py:373} INFO - Using existing BigQuery table for storing data...
[2023-10-01T20:01:31.639+0000] {bigquery.py:2326} INFO - Project is not included in destination_project_dataset_table: alt_data.green_alt_data_table; using project "nature-26092023"
[2023-10-01T20:01:31.639+0000] {gcs_to_bigquery.py:377} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'nature-26092023', 'datasetId': 'alt_data', 'tableId': 'green_alt_data_table'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://practice18/green/green_tripdata_2019-04.csv'], 'writeDisposition': 'WRITE_APPEND', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'VendorID', 'type': 'INT64', 'mode': 'NULLABLE'}, {'name': 'lpep_pickup_datetime', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'lpep_dropoff_datetime', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'store_and_fwd_flag', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'RatecodeID', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'PULocationID', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'DOLocationID', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'passenger_count', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'trip_distance', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'fare_amount', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'extra', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'mta_tax', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'tip_amount', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'tolls_amount', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'ehail_fee', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'improvement_surcharge', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'total_amount', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'payment_type', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'trip_type', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'congestion_surcharge', 'type': 'FLOAT64', 'mode': 'NULLABLE'}]}, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2023-10-01T20:01:31.640+0000] {bigquery.py:1592} INFO - Inserting job ***_Load_Green_Taxi_Data_Web_To_GCS_To_BQ_load_gcs_to_bigquery_2019_04_02T06_00_00_00_00_552552a2ef5ae206f4b46d6a01bd0a1c
[2023-10-01T20:01:46.495+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-BQ, task_id=load_gcs_to_bigquery, execution_date=20190402T060000, start_date=20231001T200131, end_date=20231001T200146
[2023-10-01T20:01:46.592+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-10-01T20:01:46.611+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
