[2023-10-01T17:55:51.070+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-05-02T06:00:00+00:00 [queued]>
[2023-10-01T17:55:51.207+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-05-02T06:00:00+00:00 [queued]>
[2023-10-01T17:55:51.208+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-10-01T17:55:51.321+0000] {taskinstance.py:1327} INFO - Executing <Task(GCSToBigQueryOperator): load_gcs_to_bigquery> on 2019-05-02 06:00:00+00:00
[2023-10-01T17:55:51.337+0000] {standard_task_runner.py:57} INFO - Started process 2644 to run task
[2023-10-01T17:55:51.342+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-BQ', 'load_gcs_to_bigquery', 'scheduled__2019-05-02T06:00:00+00:00', '--job-id', '608', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_bq.py', '--cfg-path', '/tmp/tmpikhc1c1e']
[2023-10-01T17:55:51.345+0000] {standard_task_runner.py:85} INFO - Job 608: Subtask load_gcs_to_bigquery
[2023-10-01T17:55:51.480+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-05-02T06:00:00+00:00 [running]> on host 772c7a5949f4
[2023-10-01T17:55:51.820+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-BQ' AIRFLOW_CTX_TASK_ID='load_gcs_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2019-05-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-05-02T06:00:00+00:00'
[2023-10-01T17:55:51.821+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-01T17:55:51.821+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-01T17:55:51.822+0000] {gcs_to_bigquery.py:373} INFO - Using existing BigQuery table for storing data...
[2023-10-01T17:55:51.864+0000] {bigquery.py:2326} INFO - Project is not included in destination_project_dataset_table: alt_data.green_alt_data_table; using project "nature-26092023"
[2023-10-01T17:55:51.864+0000] {gcs_to_bigquery.py:377} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'nature-26092023', 'datasetId': 'alt_data', 'tableId': 'green_alt_data_table'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://practice18/green/green_tripdata_2019-05.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2023-10-01T17:55:51.865+0000] {bigquery.py:1592} INFO - Inserting job ***_Load_Green_Taxi_Data_Web_To_GCS_To_BQ_load_gcs_to_bigquery_2019_05_02T06_00_00_00_00_23b8023be8784e0252022f056726bb82
[2023-10-01T17:55:51.873+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef8553bd90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:55:51.874+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854e8150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:55:51.875+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854e8510>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:55:52.249+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854f1090>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:55:52.251+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854f1450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:55:52.252+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854f1810>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:55:53.704+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854e8910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:55:53.707+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854e8450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:55:53.710+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef8553b690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:55:53.777+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854fc410>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:55:53.781+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854fc7d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:55:53.785+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854fcb90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:56:00.241+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef85484790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:56:00.243+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef85484b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:56:00.245+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef85484f10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:56:12.719+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854fce50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:56:12.723+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854fc710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:56:12.726+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854fc290>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:56:15.845+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef8553b450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:56:15.849+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854e86d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:56:15.852+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854e80d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:56:40.850+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef85490b90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:56:40.854+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef85490f90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:56:40.859+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854963d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:57:15.797+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-BQ, task_id=load_gcs_to_bigquery, execution_date=20190502T060000, start_date=20231001T175551, end_date=20231001T175715
[2023-10-01T17:57:15.939+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-10-01T17:57:15.958+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01T20:08:23.287+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-05-02T06:00:00+00:00 [queued]>
[2023-10-01T20:08:23.335+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-05-02T06:00:00+00:00 [queued]>
[2023-10-01T20:08:23.336+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-10-01T20:08:23.862+0000] {taskinstance.py:1327} INFO - Executing <Task(GCSToBigQueryOperator): load_gcs_to_bigquery> on 2019-05-02 06:00:00+00:00
[2023-10-01T20:08:23.874+0000] {standard_task_runner.py:57} INFO - Started process 4909 to run task
[2023-10-01T20:08:23.882+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-BQ', 'load_gcs_to_bigquery', 'scheduled__2019-05-02T06:00:00+00:00', '--job-id', '639', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_bq.py', '--cfg-path', '/tmp/tmplu_bvtdw']
[2023-10-01T20:08:23.889+0000] {standard_task_runner.py:85} INFO - Job 639: Subtask load_gcs_to_bigquery
[2023-10-01T20:08:23.952+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-05-02T06:00:00+00:00 [running]> on host 772c7a5949f4
[2023-10-01T20:08:24.187+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-BQ' AIRFLOW_CTX_TASK_ID='load_gcs_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2019-05-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-05-02T06:00:00+00:00'
[2023-10-01T20:08:24.189+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-01T20:08:24.190+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-01T20:08:24.191+0000] {gcs_to_bigquery.py:373} INFO - Using existing BigQuery table for storing data...
[2023-10-01T20:08:24.349+0000] {bigquery.py:2326} INFO - Project is not included in destination_project_dataset_table: alt_data.green_alt_data_table; using project "nature-26092023"
[2023-10-01T20:08:24.349+0000] {gcs_to_bigquery.py:377} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'nature-26092023', 'datasetId': 'alt_data', 'tableId': 'green_alt_data_table'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://practice18/green/green_tripdata_2019-05.csv'], 'writeDisposition': 'WRITE_APPEND', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'VendorID', 'type': 'INT64', 'mode': 'NULLABLE'}, {'name': 'lpep_pickup_datetime', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'lpep_dropoff_datetime', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'store_and_fwd_flag', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'RatecodeID', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'PULocationID', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'DOLocationID', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'passenger_count', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'trip_distance', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'fare_amount', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'extra', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'mta_tax', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'tip_amount', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'tolls_amount', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'ehail_fee', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'improvement_surcharge', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'total_amount', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'payment_type', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'trip_type', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'congestion_surcharge', 'type': 'FLOAT64', 'mode': 'NULLABLE'}]}, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2023-10-01T20:08:24.351+0000] {bigquery.py:1592} INFO - Inserting job ***_Load_Green_Taxi_Data_Web_To_GCS_To_BQ_load_gcs_to_bigquery_2019_05_02T06_00_00_00_00_d712c54acd0854235cfa38c83836692c
[2023-10-01T20:08:34.777+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-BQ, task_id=load_gcs_to_bigquery, execution_date=20190502T060000, start_date=20231001T200823, end_date=20231001T200834
[2023-10-01T20:08:35.017+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-10-01T20:08:35.046+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
