[2023-10-01T18:07:42.298+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2023-10-01T18:07:42.309+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-07-02T06:00:00+00:00 [queued]>
[2023-10-01T18:07:42.309+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 3
[2023-10-01T18:07:42.334+0000] {taskinstance.py:1327} INFO - Executing <Task(GCSToBigQueryOperator): load_gcs_to_bigquery> on 2019-07-02 06:00:00+00:00
[2023-10-01T18:07:42.342+0000] {standard_task_runner.py:57} INFO - Started process 2858 to run task
[2023-10-01T18:07:42.345+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-BQ', 'load_gcs_to_bigquery', 'scheduled__2019-07-02T06:00:00+00:00', '--job-id', '614', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_bq.py', '--cfg-path', '/tmp/tmpyy5dyf6l']
[2023-10-01T18:07:42.348+0000] {standard_task_runner.py:85} INFO - Job 614: Subtask load_gcs_to_bigquery
[2023-10-01T18:07:42.406+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-07-02T06:00:00+00:00 [running]> on host 772c7a5949f4
[2023-10-01T18:07:42.547+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-BQ' AIRFLOW_CTX_TASK_ID='load_gcs_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2019-07-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-07-02T06:00:00+00:00'
[2023-10-01T18:07:42.548+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-01T18:07:42.549+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-01T18:07:42.550+0000] {gcs_to_bigquery.py:373} INFO - Using existing BigQuery table for storing data...
[2023-10-01T18:07:42.594+0000] {bigquery.py:2326} INFO - Project is not included in destination_project_dataset_table: alt_data.green_alt_data_table; using project "nature-26092023"
[2023-10-01T18:07:42.594+0000] {gcs_to_bigquery.py:377} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'nature-26092023', 'datasetId': 'alt_data', 'tableId': 'green_alt_data_table'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://practice18/green/green_tripdata_2019-07.csv'], 'writeDisposition': 'WRITE_APPEND', 'ignoreUnknownValues': False, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2023-10-01T18:07:42.595+0000] {bigquery.py:1592} INFO - Inserting job ***_Load_Green_Taxi_Data_Web_To_GCS_To_BQ_load_gcs_to_bigquery_2019_07_02T06_00_00_00_00_b8e66d3fd90c38f28daa9264ea54703a
[2023-10-01T18:07:45.910+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 436, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Provided Schema does not match Table nature-26092023:alt_data.green_alt_data_table. Field VendorID has changed type from INTEGER to FLOAT
[2023-10-01T18:07:45.925+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-BQ, task_id=load_gcs_to_bigquery, execution_date=20190702T060000, start_date=20231001T180742, end_date=20231001T180745
[2023-10-01T18:07:46.419+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 614 for task load_gcs_to_bigquery (400 Provided Schema does not match Table nature-26092023:alt_data.green_alt_data_table. Field VendorID has changed type from INTEGER to FLOAT; 2858)
[2023-10-01T18:07:46.451+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-01T18:07:46.596+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
